# .github/workflows/process-artifacts.yml
name: Process GitLab Artifacts

on:
  repository_dispatch:
    types: [gitlab_artifacts_ready]

jobs:
  receive-binaries-from-gitlab:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.5.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and extract artifacts
        run: |
          apt-get update && apt-get install -y unzip curl
          curl --fail --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://code.siemens.com/api/v4/projects/401612/jobs/artifacts/deploy-to-github-community/download?job=build-and-test" \
            -o artifacts.zip
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gitlab-artifacts
          path: artifacts.zip
          retention-days: 1
      - name: Process artifacts
        run: |
          # Hier deine Verarbeitung der Artifacts
          ls -la bin/