# .github/workflows/process-artifacts.yml
name: Process GitLab Artifacts

on:
  repository_dispatch:
    types: [gitlab_artifacts_ready]

jobs:
  receive-binaries-from-gitlab:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.5.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and check artifacts
        run: |
          apt-get update && apt-get install -y unzip curl

          echo "Downloading from GitLab..."
          curl -v --fail \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
            "https://code.siemens.com/api/v4/projects/${{ github.event.client_payload.gitlab_project_id }}/jobs/${{ github.event.client_payload.gitlab_job_id }}/artifacts" \
            -o artifacts.zip

          echo "Downloaded file info:"
          ls -l artifacts.zip

          echo "Creating directory structure..."
          mkdir -p bin/1500 bin/llvm

          echo "Extracting artifacts..."
          unzip artifacts.zip 'bin/1500/*' 'bin/llvm/*'
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gitlab-artifacts
          path: artifacts.zip
          retention-days: 1
      - name: Process artifacts
        run: |
          # Hier deine Verarbeitung der Artifacts
          ls -la bin/