name: Dispatch Test

on:
  repository_dispatch:
    types: [gitlab_artifacts_ready]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: |
          echo "Payload received:"
          echo "Project ID: ${{ github.event.client_payload.gitlab_project_id }}"
          echo "Job ID: ${{ github.event.client_payload.gitlab_job_id }}"
          echo "Pipeline ID: ${{ github.event.client_payload.gitlab_pipeline_id }}"
          echo "Commit Ref: ${{ github.event.client_payload.gitlab_commit_ref }}"
          echo "Custom Branch: ${{ github.event.client_payload.custom_branch }}"

      - name: Checkout this branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.custom_branch }}
